name: Build with pnpm or yarn and Save Artifact to S3

on:
  workflow_call:
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      pnpm_versions:
        required: false
        description: "pnpm version which want to use"
        type: number
        default: 8 
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_repo:
        description: 'Release Repository'
        required: true
        default: ""
        type: string
      prod_s3_bucket:
        description: 'prod env S3 Bucket Name'
        required: true
        default: ""
        type: string
      prod_front_s3_bucket:
        description: 'prod env Front S3 Bucket Name'
        required: true
        default: ""
        type: string
      prod_aws_account:
        description: 'prod AWS Account'
        required: true
        default: ""
        type: string
      qa_s3_bucket:
        description: 'qa env S3 Bucket Name'
        required: false
        default: ""
        type: string
      qa_front_s3_bucket:
        description: 'qa env Front S3 Bucket Name'
        required: false
        default: ""
        type: string
      qa_aws_account:
        description: 'qa AWS Account'
        required: false
        default: ""
        type: string
      dev_s3_bucket:
        description: 'DEV(hotfix) env S3 Bucket Name'
        required: false
        default: ""
        type: string
      dev_front_s3_bucket:
        description: 'DEV(hotfix) env Front S3 Bucket Name'
        required: false
        default: ""
        type: string
      dev_aws_account:
        description: 'DEV(hotfix) AWS Account'
        required: false
        default: ""
        type: string 
      qa_cloudfront_distribution_id:
        description: 'qa Cloudfront Distribution ID'
        required: false
        default: ""
        type: string
      prod_cloudfront_distribution_id:
        description: 'prod Cloudfront Distribution ID'
        required: false
        default: ""
        type: string
      s3_prefix:
        description: 'S3 prefix for deploy.zip'
        required: true
        default: ""
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    name: Build Deploy
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: backend-sw-development-team4/${{ inputs.release_repo }}
          ref: refs/heads/release
          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

      - name: Setup pnpm
        if: ${{ inputs.s3_prefix != 'frontend' }}
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install pnpm dependencies
        if: ${{ inputs.s3_prefix != 'frontend' }}
        working-directory: ./
        run: |
          pnpm install
      
      - name: Pnpm build
        if: ${{ inputs.s3_prefix != 'frontend' }}
        working-directory: ./
        run: |
          if [ ${{ inputs.release_env }}  == "qa" ]; then
            pnpm run build:qa
          elif [ ${{ inputs.release_env }}  == "prod" ]; then
            pnpm run build:prod
          fi

      - name: Setup yarn
        if: ${{ inputs.s3_prefix == 'frontend' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn
      
      - name: Install dependencies yarn
        if: ${{ inputs.s3_prefix == 'frontend' }}
        working-directory: ./
        run: |
          yarn install
      
      - name: Yarn Build
        if: ${{ inputs.s3_prefix == 'frontend' }}
        working-directory: ./
        run: |
          if [ ${{ inputs.release_env }}  == "qa" ]; then
            yarn build:qa
          elif [ ${{ inputs.release_env }}  == "prod" ]; then
            yarn build:prod
          fi

          ls -al
      
      - name: Configure qa AWS credentials
        if: ${{ inputs.release_env == 'qa' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::060636281042:role/role-sp012-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
      
      - name: Configure prod AWS credentials
        if: ${{ inputs.release_env == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::497796310523:role/role-sp012-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
      
      - name: Push to S3 Front Bucket
        working-directory: ./
        run: |
         cd dist
         if [ ${{ inputs.release_env }}  == "qa" ]; then
            aws s3 sync ./ s3://${{ inputs.qa_front_s3_bucket }} --delete
         elif [ ${{ inputs.release_env }}  == "prod" ]; then
            aws s3 sync ./ s3://${{ inputs.prod_front_s3_bucket }} --delete
         fi


      - name: Creat CloudFront Invalidations
        working-directory: ./
        run: |
          if [ ${{ inputs.release_env }}  == "qa" ]; then
            aws cloudfront create-invalidation --distribution-id ${{ inputs.qa_cloudfront_distribution_id }} --paths "/*" 
          elif [ ${{ inputs.release_env }}  == "prod" ]; then
            aws cloudfront create-invalidation --distribution-id ${{ inputs.prod_cloudfront_distribution_id }} --paths "/*" 
          fi
      
      - name: Push to S3 CICD Bucket
        working-directory: ./
        run: |
         cd dist
         zip -qry frontend.zip .
         if [ ${{ inputs.release_env }}  == "qa" ]; then
            aws s3 cp frontend.zip s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/frontend.zip --region us-east-1
         elif [ ${{ inputs.release_env }}  == "prod" ]; then
            aws s3 cp frontend.zip s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/frontend.zip --region us-east-1
         fi
      
         
         
