name: Build with pnpm or yarn and Save Artifact to S3

on:
  workflow_call:
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      pnpm_versions:
        required: false
        description: "pnpm version which want to use"
        type: number
        default: 8 
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_repo:
        description: 'Release Repository'
        required: true
        default: ""
        type: string
      prod_s3_bucket:
        description: 'prod env S3 Bucket Name'
        required: true
        default: ""
        type: string
      prod_aws_account:
        description: 'prod AWS Account'
        required: true
        default: ""
        type: string
      qa_s3_bucket:
        description: 'qa env S3 Bucket Name'
        required: false
        default: ""
        type: string
      qa_aws_account:
        description: 'qa AWS Account'
        required: false
        default: ""
        type: string
      dev_s3_bucket:
        description: 'DEV(hotfix) env S3 Bucket Name'
        required: false
        default: ""
        type: string
      dev_aws_account:
        description: 'DEV(hotfix) AWS Account'
        required: false
        default: ""
        type: string
      s3_prefix:
        description: 'S3 prefix for deploy.zip'
        required: true
        default: ""
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  qa-build-deploy:
    name: qa Build Deploy
    if: ${{ inputs.release_env == 'qa' }}
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: backend-sw-development-team4/${{ inputs.release_repo }}
          ref: refs/heads/release
          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

      - name: Pnpn build release
        if: ${{ inputs.s3_prefix != 'backend' }}
        env:
          PAT_TOKEN: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
          REPO_OWNER: backend-sw-development-team4
          REPO_NAME: ${{ inputs.release_repo }}
          REF_NAME: release
          WORKING_DIR: ./
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: |
          if [ ${{ inputs.s3_prefix }}  == "license" ]; then
            curl -X POST -H "Authorization: Bearer ${PAT_TOKEN}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/workflows/jira_release_build_release.yml/dispatches"  -d '{"ref":"refs/heads/release", "inputs": {"working_dir": "'"${WORKING_DIR}"'", "release_version": "'"${RELEASE_VERSION}"'"}}'
          else
            curl -X POST -H "Authorization: Bearer ${PAT_TOKEN}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/workflows/jira-release-build-release.yml/dispatches"  -d '{"ref":"refs/heads/release", "inputs": {"working_dir": "'"${WORKING_DIR}"'", "release_version": "'"${RELEASE_VERSION}"'"}}'
          fi
          
        
      

      - name: Setup yarn
        if: ${{ inputs.s3_prefix == 'backend' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.12
          cache: yarn

      - name: Install dependencies yarn
        if: ${{ inputs.s3_prefix == 'backend' }}
        working-directory: ./
        run: |
          yarn install

      - name: Configure AWS credentials
        if: ${{ inputs.s3_prefix == 'backend' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::060636281042:role/role-sp012-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1

      - name: Push build artifact to S3 Bucket
        if: ${{ inputs.s3_prefix == 'backend' }}
        working-directory: ${{ inputs.working_dir }}
        run: |
          # Check if env file exists in the specific release version path
          if ! aws s3 ls s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env > /dev/null 2>&1; then
            aws s3 cp s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/env s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env
            echo "default env copy done"
          else
            echo "env already exists. No need to copy."
          fi

          # Change Codedeploy script
          env_script="aws s3 cp s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env ."
          sed -i "/^aws s3 cp/ s|.*|${env_script}|" ./scripts/deploy.sh

          # Deploy
          zip -qry deploy.zip .
          aws s3 cp ./deploy.zip s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/deploy.zip --only-show-errors  --metadata version=${{ inputs.release_version }}

  prod-deploy:
    name: prod Deploy
    if: ${{ inputs.release_env == 'prod' }}
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::060636281042:role/role-sp012-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1

      - name: Get qa code from S3 Bucket
        working-directory: ${{ inputs.working_dir }}
        run: |
          aws s3 cp s3://${{ inputs.qa_s3_bucket }}/${{ inputs.s3_prefix }}/deploy.zip . --only-show-errors 

      - name: ReConfigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::497796310523:role/role-sp012-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
          
      - name: Push to S3 Bucket
        run: |
          # Unzip qa deploy.zip
          unzip -oq deploy.zip
          rm  deploy.zip

          # Check if env file exists in the specific release version path
          if ! aws s3 ls s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env > /dev/null 2>&1; then
            aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/env s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env
            echo "default env copy done"
          else
            echo "env already exists. No need to copy."
          fi

          # Change Codedeploy script
          env_script="aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env ."
          sed -i "/^aws s3 cp/ s|.*|${env_script}|" ./scripts/deploy.sh
          
          # Deploy
          zip -qry deploy.zip .
          aws s3 cp ./deploy.zip s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/deploy.zip --only-show-errors  --metadata version=${{ inputs.release_version }}
  
  hotfix-deploy:
    name: prod Deploy
    if: ${{ inputs.release_env == 'hotfix' }}
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::060636281042:role/role-sp012-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1

      - name: Get qa code from S3 Bucket
        working-directory: ${{ inputs.working_dir }}
        run: |
          aws s3 cp s3://${{ inputs.qa_s3_bucket }}/hotfix/${{ inputs.s3_prefix }}/deploy.zip . --only-show-errors 

      - name: ReConfigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::497796310523:role/role-sp012-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
          
      - name: Push to S3 Bucket
        run: |
          # Unzip qa deploy.zip
          unzip -oq deploy.zip
          rm  deploy.zip

          # Check if env file exists in the specific release version path
          if ! aws s3 ls s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env > /dev/null 2>&1; then
            aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/env s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env
            echo "default env copy done"
          else
            echo "env already exists. No need to copy."
          fi

          # Change Codedeploy script
          env_script="aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env ."
          sed -i "/^aws s3 cp/ s|.*|${env_script}|" ./scripts/deploy.sh
          
          # Deploy
          zip -qry deploy.zip .
          aws s3 cp ./deploy.zip s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/deploy.zip --only-show-errors  --metadata version=${{ inputs.release_version }}

  #hotfix-deploy:
  #  name: Hotfix Deploy
  #  if: ${{ startsWith(inputs.release_env, 'hotfix') }}
  #  runs-on: ubuntu-latest
  #  environment: main
  #  steps:
  #    - name: Configure AWS credentials
  #      uses: aws-actions/configure-aws-credentials@v2
  #      with:
  #        role-to-assume: arn:aws:iam::540528117317:role/role-sp012-dev-github-ci
  #        role-session-name: GitHub-Actions-Assume
  #        aws-region: ap-northeast-2

  #    - name: Get Hitfix code from S3 Bucket
  #      working-directory: ${{ inputs.working_dir }}
  #      run: |
  #        aws s3 cp s3://${{ inputs.dev_s3_bucket }}/${{ inputs.s3_prefix }}/hotfix/deploy.zip . --only-show-errors 

  #    - name: ReConfigure AWS credentials
  #      uses: aws-actions/configure-aws-credentials@v2
  #      with:
  #        role-to-assume: arn:aws:iam::497796310523:role/role-sp012-prod-github-ci
  #        role-session-name: GitHub-Actions-Assume
  #        aws-region: us-east-1

  #    - name: Push to S3 Bucket
  #      run: |
          # Unzip qa deploy.zip
  #        unzip -oq deploy.zip
  #        rm env deploy.zip

          # Check if env file exists in the specific release version path
  #        if ! aws s3 ls s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env > /dev/null 2>&1; then
  #          aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/env s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env
  #          echo "default env copy done"
  #        else
  #          echo "env already exists. No need to copy."
  #        fi

          # Change Codedeploy script
  #        env_script="aws s3 cp s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/${{ inputs.release_version }}/env ."
  #        sed -i '/^aws s3 cp/ s/.*/${env_script}/' ./scripts/deploy.sh
          
          # Deploy
  #        zip -qry deploy.zip .
  #        aws s3 cp ./deploy.zip s3://${{ inputs.prod_s3_bucket }}/${{ inputs.s3_prefix }}/deploy.zip --only-show-errors  --metadata version=${{ inputs.release_version }}
