name: source code quality check mopl all service

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_MANAGEPACKAGE_TOKEN:
        required: false
        description: "If not provided, the repo creds will be used."

jobs:
  coverity:
    environment: main
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    container:
      image: ghcr.io/hanwhavision/coverity-github:1.0.1
      options: --user root
      credentials:
        username: jenkins
        password: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
  
    name: Quality Check non-compile Project
    strategy:
      matrix:
        non-compile_Project: [mopl-admin, mopl-apartment-service, mopl-audit-service, mopl-authn-service, mopl-batch-service, mopl-community-service, mopl-device-service, mopl-user-service, mopl-vote-service, mopl-user-app]
        compile_Project: [mopl-user-app-android, mopl-user-IOS, mopl-Apartment-guard-app]
    steps:
      - name: Coverity non-compile Project Report 
        run: |
          echo "CI_STEP_CoverityReport"
          for project in "${{ matrix.non-compile_Project }}"; do
            python3 /home/jenkins/coverity_utils/cov_auto_report.py Cloud non-compile "$project"
          done

      - name: Coverity compile Project Report 
        run: |
          echo "CI_STEP_CoverityReport"
          for project in "${{ matrix.compile_Project }}"; do
            python3 /home/jenkins/coverity_utils/cov_auto_report.py Cloud compile "$project"
          done
