name: Create Github Release

run-name: ${{ github.event.sender.login }} executes 'create_release' action for ${{ inputs.jira_key }} - ${{ inputs.release_version }}

on:
  workflow_dispatch:
    inputs:
      jira_key:
        description: 'Jira Project Key'
        required: true
        default: 'MCP'
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      release_env:
        description: 'Release environment'
        required: true
        default: ""
        type: string

permissions: write-all


jobs:
  initial_setting:
    outputs:
      git_org: ${{ steps.set_env.outputs.git_org }}
      repo: ${{ steps.set_env.outputs.repo }}
      release_branch: ${{ steps.set_env.outputs.release_branch }}
      project_name: ${{ steps.set_env.outputs.project_name }}
    name: Initial Setting
    runs-on: ubuntu-latest
    steps:
      - name: set env
        id: set_env
        run: |
          git_org=backend-sw-development-team4
          repo=smartparking-gitops
          release_branch=main
          project_name=Mopl

          echo "git_org=$git_org" >> $GITHUB_OUTPUT
          echo "repo=$repo" >> $GITHUB_OUTPUT
          echo "release_branch=$release_branch" >> $GITHUB_OUTPUT
          echo "project_name=$project_name" >> $GITHUB_OUTPUT
  # QA jira Release
  jira-qa-release:
    name: jira Release QA
    needs: initial_setting
    if: ${{ inputs.release_env == 'QA' }}
    uses: hanwhavision/keeper-github-action/.github/workflows/pbd-jira-qa-release.yaml@release
    secrets: inherit
    with:
      release_env: ${{ inputs.release_env }}
      repository_org: ${{ needs.initial_setting.outputs.git_org }}
      repository_name: ${{ needs.initial_setting.outputs.repo }}
      repository_ref: ${{ needs.initial_setting.outputs.release_branch }}
      release_version: ${{ inputs.release_version }}
      project_name: ${{ needs.initial_setting.outputs.project_name }}

  # PROD jira Release
  jira-prod-release:
    name: jira Release PROD
    needs: initial_setting
    if: ${{ inputs.release_env == 'PROD' }}
    uses: hanwhavision/keeper-github-action/.github/workflows/pbd-jira-prod-release.yaml@release
    secrets: inherit
    with:
      release_env: ${{ inputs.release_env }}
      repository_org: ${{ needs.initial_setting.outputs.git_org }}
      repository_name: ${{ needs.initial_setting.outputs.repo }}
      repository_ref: ${{ needs.initial_setting.outputs.release_branch }}
      release_version: ${{ inputs.release_version }}
      project_name: ${{ needs.initial_setting.outputs.project_name }}

