name: Build and Push container image to aws ecr using dockerfile for frontend

on:
  workflow_call:
    outputs:
      version:
        description: "Version number from  deployment"
        value: ${{ jobs.create-tag.outputs.version }}
    inputs:
      image_name:
        required: false
        description: "Name of docker registry to publish. Does not need ghcr.io/cloud-development-team/ in front."
        type: string
      build_args:
        required: false
        description: "Name of docker registry to publish. Does not need ghcr.io/cloud-development-team/ in front."
        type: string
      image_tag:
        required: false
        description: "Additional tag for cretead image"
        type: string
      dockerfile_name:
        required: false
        description: "dockerfile's name if it's different than the conventional name"
        type: string
        default: "Dockerfile"
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      ecr_region:
        required: true
        description: "AWS region to upload container image to ECR"
        type: string
      ecr_registry:
        required: true
        type: string
      ecr_repository:
        required: true
        description: "Name of ECR repository"
        type: string
      environment_name:
        required: false
        description: "Environment name for tagging"
        type: string
        default: "dev"
    secrets:
      GH_MANAGEPACKAGE_TOKEN:
        required: true
      MOPL_CODEFREEZE:
        required: false
      MOPL_AWS_ACCESS_KEY_ID:
        required: true
      MOPL_AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKER_BUILD_ARGS:
        required: false

jobs:
  create-tag:
    outputs:
      version: ${{ steps.version.outputs.version }}
    name: Create tag for new image
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        run: |
          if [[ "${{ inputs.image_tag }}" != '' ]]; then
            echo "version=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ vars.ENV }}-$(git rev-parse --short HEAD)-$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Result
        run: |
          echo "version=${{ steps.version.outputs.version }}"

  dev-build-and-push-ecr:
    name: Container image build and push to ecr for dev
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment_name }}
    needs: create-tag
    if: ${{ vars.ENV  == 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712975332:role/HV-platform-tf-automation
          role-session-name: githubactions
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set develop env file
        run: |
          cp ./env/${{ vars.ENV }}/.env ./env

      - name: Build, tag, and push image to Amazon ECR for DEV
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_name }}
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args: |
            NPM_TOKEN=${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
          tags: |
            "${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ needs.create-tag.outputs.version }}"

  qa-build-and-push-ecr:
    name: Container image build and push to ecr for qa and prod
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment_name }}
    needs: create-tag
    if: ${{ vars.ENV  == 'qa' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712975332:role/HV-platform-tf-automation
          role-session-name: githubactions
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set qa env file
        run: |
          cp ./env/${{ vars.ENV }}/.env ./env

      - name: Build, tag, and push image to Amazon ECR for QA
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_name }}
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args: |
            NPM_TOKEN=${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
          tags: |
            "${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ needs.create-tag.outputs.version }}"

      - name: Set prod env file
        run: |
          rm ./env
          cp ./env/prod/.env ./env

      - name: Build, tag, and push image to Amazon ECR for PROD
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_name }}
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args: |
            NPM_TOKEN=${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
          tags: |
            "${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:prod-${{ needs.create-tag.outputs.version }}"

