name: Manual Static Analysis

run-name: '${{ github.event.sender.login }} executed manual static analysis'

on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        description: 'Repository'
        required: true
        type: choice
        default: 'Choose Repo Name'
        options:  
          - saleshub-frontend
          - saleshub-backend
          - saleshub-license-server
          - saleshub-license-helper
      BUILD_PATH:
        description: 'Build target path'
        required: true
        type: string
        default: '.'
      BRANCH:
        description: 'Target Branch'
        required: true
        type: string
        default: 'develop, release, main, etc...'
      QUALITY_REPORT:
        description: 'Make static analysis report for CIM'
        required: false
        type: boolean
        default: true

jobs:
  static-analysis:
    name: Analysis code quality
    uses: backend-sw-development-team4/.github/.github/workflows/static-analysis.yaml@main
    with:
      REPO_NAME: ${{ inputs.REPO_NAME }}
      BUILD_PATH: ${{ inputs.BUILD_PATH }}
      QUALITY_REPORT: ${{ inputs.QUALITY_REPORT }}
      DISPATCH: true
      BRANCH: ${{ inputs.BRANCH }}
    secrets: inherit